# This file stores configurations for your Shopify app.

scopes = "read_products,write_products,read_script_tags,write_script_tags,read_products,read_shipping,read_customers,unauthenticated_write_customers,read_price_rules,write_price_rules,read_discounts,write_discounts"