name = "order-discount-ext"
type = "order_discounts"
api_version = "2023-01"

[build]
command = ""
path = "dist/function.wasm"

[ui.paths]
create = "/volume/:functionId/new?functionId=:functionId"
details = "/volume/:functionId/detail?functionId=:functionId&id=:id"